{% set name = "trio" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 670a52d3115d0e879e1ac838a4eb999af32f858163e3a704fe4839de2a676070

build:
  skip: true  # [py<35]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - attrs >=19.2.0
    - sortedcontainers
    - async_generator >=1.9
    - contextvars >=2.1  # [py<37]
    - idna
    - outcome
    - sniffio
    - cffi >=1.14  # [win]

test:
  imports:
    - trio
    - trio._core
    - trio._core.tests
    - trio._core.tests.test_multierror_scripts
    - trio.testing
    - trio.tests

about:
  home: https://github.com/python-trio/trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An async/await-native I/O library for humans and snake people
  doc_url: https://trio.readthedocs.io/
  dev_url: https://github.com/python-trio/trio

extra:
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
