{% set name = "trio" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16f89f7dcc8f7b9dcdec1fcd863e0c039af6d0f9a22f8dfd56f75d75ec73fd48

build:
  skip: true  # [py<37]
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - attrs >=20.1.0
    - sortedcontainers
    - idna
    - outcome
    - sniffio >=1.3.0
    - cffi >=1.14  # [win and not python_impl == 'pypy']
    - exceptiongroup >=1.0.0rc9  # [py<311]

test:
  imports:
    - trio
    - trio._core
    - trio._core._tests
    - trio._core._tests.test_multierror_scripts
    - trio.testing
    - trio._tests
    - trio._tools
    - trio._subprocess_platform
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-trio/trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An async/await-native I/O library for humans and snake people
  doc_url: https://trio.readthedocs.io/
  dev_url: https://github.com/python-trio/trio

extra:
  recipe-maintainers:
    - dhirschfeld
    - nicoddemus
    - synapticarbors
