{% set name = "trio" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dcc95ab1726b2da054afea8fd761af74bad79bd52381b84eae408e983c76831

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=64
  run:
    - python
    - attrs >=23.2.0
    - sortedcontainers
    - idna
    - outcome
    - sniffio >=1.3.0
    - cffi >=1.14  # [win and not python_impl == 'pypy']
    - exceptiongroup             # [py<311]

test:
  imports:
    - trio
    - trio.testing
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-trio/trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An async/await-native I/O library for humans and snake people
  doc_url: https://trio.readthedocs.io/
  dev_url: https://github.com/python-trio/trio

extra:
  recipe-maintainers:
    - dhirschfeld
    - nicoddemus
    - synapticarbors
